version: '3.5'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-public
    volumes:
      - ./config/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.dashboard.rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      traefik.http.routers.dashboard.entrypoints: "traefik"
      traefik.http.routers.dashboard.service: "api@internal"

networks:
  traefik-public:
    external: true
