version: '3'

services:
  app:
    image: nextcloud:25.0.3-apache
    container_name: nextcloud
    networks:
      - "traefik-public"
    expose:
      - "80"
    volumes:
      - app:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
    environment:
     # - "TRUSTED_PROXIES=172.19.0.0/24"
     # - "APACHE_DISABLE_REWRITE_IP=1"
      - "NEXTCLOUD_DATA_DIR=/var/www/html/data"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.nextcloud.rule=Host(`drive.eecist.lan`)"
      - "traefik.http.routers.nextcloud.entrypoints=http"
#      - "traefik.http.routers.nextcloud.middlewares=sh_nc"
#      - "traefik.http.middlewares.sh_nc.chain.middlewares=SecHeader@file,nextcloud-redir@file"

  db:
    image: postgres:latest
    container_name: nextcloud_db
    networks:
      - "traefik-public"
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=nextcloud"
      - "POSTGRES_USER=eecist"
      - "POSTGRES_PASSWORD=lejaguardebamako"

networks:
  traefik-public:
    external: true

volumes:
  app:
  db:
