version: '3.8'

services:
  eewebsite:
    image: sreycoyrehourcq/cist-ee:main
    networks:
      - "traefik-public"
    #tty: true
    volumes:
      - ./website:/project/website
    command: "render ./website"

  nginx:
    image: flashspys/nginx-static
    networks:
      - "traefik-public"
    expose:
      - 80 
    volumes: 
      - /home/reyman/Projets/Guix-ified/workshop/cist-EE/eecist-offline-rpi/website/website/_site:/static
    depends_on:
      eewebsite:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
#     - "traefik.http.routers.nextcloud.rule=Host(`website.eecist.lan`)"
      - "traefik.http.routers.website.rule=Host(`localhost`)"
      - "traefik.http.routers.website.entrypoints=http"
   
networks:
  traefik-public:
    external: true

