version: '3.3'

services:
  cran:
    image: eecist/minicran
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /home/eecist/RPIConfig/Volumes/minicran:/var/www/html
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.cran.rule=Host(`minicran.eecist.lan`)
      - traefik.http.routers.cran.entrypoints=http
      - traefik.http.services.cran.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
